---
title: "COVID Excess Death"
author: Viguen Poghosyan, Davit Sargsyan
version: 2.0
output:
  html_notebook:
    highlight: tango
    toc: true
    toc_float: true
    toc_depth: 6
    number_sections: yes
    code_folding: hide
---

Date: `r date()`

# Setup
```{r setup}
require(data.table)
require(ggplot2)
require(nlme)
```

```{r}
dt1 <- data.table(read.csv("data/JOINT_HistRec_ETS_Results_short.csv"))
colnames(dt1)

head(dt1)
```
# Data formating
```{r}
dt2 <- dt1[, .(Date = as.Date(paste0(dt1$Month_Code,
                                     "/01"),
                              format = "%Y/%m/%d"),
               State = factor(State),
               Cause = factor(ICD.10.113.Cause.List,
                              levels = unique(ICD.10.113.Cause.List),
                              labels = gsub(x = unique(ICD.10.113.Cause.List),
                                            pattern = "#",
                                            replacement = "")),
               
               Rate = 10^6*(dt1$Deaths + 1)/(daysmonth*(Population + 1)))]
```

```{r}
levels(dt2$State)
levels(dt2$Cause)
```

# Training/Testing/COVID
```{r}
dt2$set <- "trn"

dt2$set[dt2$Date >= "2019-02-01" &
          dt2$Date < "2019-03-01"] <- "tst"

dt2$set[dt2$Date >= "2019-03-01"] <- "cvd"
```

# Output lists
```{r}
betas <- list()
mape <- list()
mape_state <- list()
models <- list()
```

# Modeling
```{r}
for (i in 1:nlevels(dt2$Cause)) {
  # Subset data
  cod <- levels(dt2$Cause)[i]
  
  tmp <- droplevels(dt2[Date < "2022-07-01" &
                          Cause == cod,])
  
  tmp$dt <- as.numeric(tmp$Date)
  tmp$dt_sqr <- tmp$dt^2
  
  # LM
  m1 <- lm(Rate ~ (dt + dt_sqr)*State,
           data = tmp[set == "trn"])
  
  tmp$prd1 <- predict(m1,
                      newdata = tmp)
  
  # Plot
  p1 <- ggplot(tmp,
               aes(x = Date,
                   y = Rate,
                   group = Cause)) +
    facet_wrap(~ State) +
    geom_line(color = "gray") +
    geom_line(aes(x = Date,
                  y = prd1),
              color = "green") +
    scale_x_continuous(breaks = seq.Date(from = min(dt2$Date),
                                         to = max(dt2$Date),
                                         by = 365.25)) +
    ggtitle(cod) +
    theme_bw() +
    theme(legend.position = "none",
          axis.text.x = element_text(angle = 90,
                                     hjust = 1))
  
  m3 <- try({
    # NLME
    m3 <- nlme(Rate ~ b0 + b1*dt + b2*dt^2 + b3*sin(b4 + b5*dt),
               data = tmp[set == "trn"],
               random = b0 + b1 + b2 + b3 + b4 + b5 ~ 1 | State,
               fixed = b0 + b1 + b2 + b3 + b4 + b5 ~ 1,
               start = list(fixed = c(b0 = m1$coefficients[1], # linear intercept
                                      b1 = m1$coefficients[2], # linear slope
                                      b2 = m1$coefficients[3], # square term, i.e. non-linearity of the trend
                                      b3 = 10000, # wave magnitude
                                      b4 = 1, # sin shift to the left
                                      b5 = 0.018))) # wave length(> 1 shortens, < 1 elongates))
  })
  if(class(m3)[1] != "try-error") {
  
    tmp$prd3 <- predict(m3,
                        newdata = tmp)
    # Save coefficients
    betas[[i]] <- m3$coefficients$fixed
    
    # Save Mean Absolute Percent Error (MAPE)
    ## All states
    mape[[i]] <- tmp[, .(mape = 100*mean(abs(Rate - prd3)/(Rate))),
                     by = set]
    
    ## By State
    mape_state[[i]] <- tmp[, .(mape = 100*mean(abs(Rate - prd3)/(Rate))),
                           by = list(State,
                                     set)]
    # Add predicted curve
    p1 <- p1 +
      geom_line(data = tmp,
                aes(x = Date,
                    y = prd3),
                color = "blue")
  }
  
  # Save plot
  tiff(filename = paste0("tmp/",
                         cod,
                         ".tiff"),
       height = 10,
       width = 10,
       units = 'in',
       res = 300,
       compression = "lzw+p")
  print(p1)
  graphics.off()
}
```

# Table 1: Betas
```{r}
names(betas) <- levels(dt2$Cause)

lapply(X = betas,
       FUN = is.null)
betas[[8]] <- NULL

t1 <- do.call("rbind",
              betas)

t1

write.csv(t1,
          file = "tmp/betas.csv",
          row.names = TRUE)
```

# Table 2: MAPE, all states
```{r}
names(mape) <- levels(dt2$Cause)
t2 <- rbindlist(mape,
                use.names = TRUE)
t2 <- data.table(`Cause of Death` = rep(levels(dt2$Cause),
                                        each = 3),
                 t2)
t2$set <- factor(t2$set,
                 levels = c("trn",
                            "tst",
                            "cvd"),
                 labels = c("Training",
                            "Testing",
                            "COVID-19"))

t2 <- dcast.data.table(t2,
                       `Cause of Death` ~ set,
                       value.var = "mape")

t2

write.csv(t2,
          file = "tmp/mape.csv",
          row.names = FALSE)
```

# Table 3: MAPE, by State
```{r}
out <- list()
for (i in 1:length(mape_state)) {
  out[[i]] <- data.table(`Cause of Death` = levels(dt2$Cause)[i],
                                mape_state[[i]])
}

out[[4]] <- NULL
out[[7]] <- NULL
t3 <- rbindlist(out)

t3$set <- factor(t3$set,
                 levels = c("trn",
                            "tst",
                            "cvd"),
                 labels = c("Training",
                            "Testing",
                            "COVID-19"))

t3 <- dcast.data.table(t3,
                       `Cause of Death` + State ~ set,
                       value.var = "mape")

head(t3)

write.csv(t3,
          file = "tmp/mape_state.csv",
          row.names = FALSE)
```

# Session
```{r}
sessionInfo()
```